// Auto-generated by scripts/generate-env.js — do not edit manually
export const environment = {
  production: false,
  emailjs: {
    serviceId: "service_w8c3wrr",
    templateId: "template_c0xfi54",
    publicKey: "84qVYcuKUDLfGcmEH",
  },
  firebase: {
    apiKey: "AIzaSyD8o5pjZEF5vAHVpiiaR5sVlB04ieytAO4",
    authDomain: "portfolio-testim.firebaseapp.com",
    projectId: "portfolio-testim",
    storageBucket: "portfolio-testim.firebasestorage.app",
    messagingSenderId: "748547061592",
    appId: "1:748547061592:web:4e4e7a4b959eba962c172d",
    measurementId: "G-EGH118CSFW",
  },
  apiUrl: "http://localhost:3000",
  enableAnalytics: false,
  enableServiceWorker: false,
  cacheTimeout: 30000,
  version: "1.0.0",
  debugMode: true,
  logLevel: "debug",
};
