// Auto-generated by scripts/generate-env.js — do not edit manually
export const environment = {
  production: false,
  emailjs: {
    serviceId: "service_w8c3wrr",
    templateId: "template_c0xfi54",
    publicKey: "84qVYcuKUDLfGcmEH",
  },
  apiUrl: "http://localhost:3000",
  enableAnalytics: false,
  enableServiceWorker: false,
  cacheTimeout: 30000,
  version: "1.0.0",
  debugMode: true,
  logLevel: "debug",
};
