const fs = require("fs");
const path = require("path");

// Load .env file locally if it exists (ignored in CI/Netlify)
const dotenvPath = path.resolve(__dirname, "../.env");
if (fs.existsSync(dotenvPath)) {
  require("dotenv").config({ path: dotenvPath });
}

const content = `// Auto-generated by scripts/generate-env.js — do not edit manually
export const environment = {
  production: ${process.env.NODE_ENV === "production"},
  emailjs: {
    serviceId: "${process.env.EMAILJS_SERVICE_ID || ""}",
    templateId: "${process.env.EMAILJS_TEMPLATE_ID || ""}",
    publicKey: "${process.env.EMAILJS_PUBLIC_KEY || ""}",
  },
  firebase: {
    apiKey: "${process.env.FIREBASE_API_KEY || ""}",
    authDomain: "${process.env.FIREBASE_AUTH_DOMAIN || ""}",
    projectId: "${process.env.FIREBASE_PROJECT_ID || ""}",
    storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET || ""}",
    messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || ""}",
    appId: "${process.env.FIREBASE_APP_ID || ""}",
    measurementId: "${process.env.FIREBASE_MEASUREMENT_ID || ""}",
  },
  apiUrl: "${process.env.API_URL || "http://localhost:3000"}",
  enableAnalytics: false,
  enableServiceWorker: ${process.env.NODE_ENV === "production"},
  cacheTimeout: 30000,
  version: "1.0.0",
  debugMode: ${process.env.NODE_ENV !== "production"},
  logLevel: "${process.env.NODE_ENV === "production" ? "error" : "debug"}",
};
`;

const outPath = path.resolve(__dirname, "../src/environments/environment.ts");
fs.writeFileSync(outPath, content);

const outProdPath = path.resolve(__dirname, "../src/environments/environment.prod.ts");
fs.writeFileSync(outProdPath, content.replace(
  "production: false",
  "production: true"
).replace(
  "debugMode: true",
  "debugMode: false"
).replace(
  'logLevel: "debug"',
  'logLevel: "error"'
));

console.log("✅ environment.ts generated");
console.log("✅ environment.prod.ts generated");
